class_loader_paths:
  python:
    - "/nfs/raid88/u10/users/hqiu_ad/repos/text-open/src/python/serif/model/impl/stanza_adapter2/a2t_compound_basic_nlp.py"
  java: []
models:
  - model_name: "StanzaDriver"
    kwargs:
      lang: "en"
      model_dir: "/nfs/raid88/u10/users/hqiu_ad/data/common/stanza/1.4.2"
      processors: "tokenize,mwt,pos,ner,constituency"
  - model_name: "StanzaAdapter"
    kwargs:
      lang: "en"
      stage_to_add: "sentence_splitting, tokenization, parsing"
#  - model_name: "BeneparParser"
#    kwargs:
#      model: "/home/hqiu/nltk_data/models/benepar_en3"
#      add_heads: True
#  - model_name: "NounPhraseMentionModel"
#    kwargs:
#      modify_existing_mention: True
  - model_name: "PronounMentionModel"
    kwargs:
      modify_existing_mention: True
  - model_name: "StanzaAdapter"
    kwargs:
      lang: "en"
      stage_to_add: "ner"
  - model_name: "NounPhraseMentionModelNERDeduplication"
    kwargs: {}
#  - model_name: "AllenNLPCoreferenceModel"
#    kwargs:
#      model: "/nfs/raid88/u10/users/hqiu_ad/data/common/allennlp/coref-spanbert-large-2021.03.10.tar.gz"
  - model_name: "GenericEventDetector"
    kwargs:
      candidate_generation_method: "PARSE_TREE"
      candidate_cannot_overlap_name_pron: True